apiVersion: apps/v1
kind: Deployment
metadata:
  name: javadep
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: java
        image: saikkumar1606/javaweb:v1
