apiVersion: apps/v1
kind: Deployment
metadata:
  name: htmldep
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: java
        image: saikkumar1606/canary-v1-v2:v1
